# Generated by Django 3.2.4 on 2021-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='telephone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
